apiVersion: v1
kind: PersistentVolume
metadata:
  name: hpc-cache-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /testdata/
    server: aksdemocache.local
    readOnly: false