apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis-zone1
  name: redis-zone1
spec:
  nodeSelector:
    topology.kubernetes.io/zone: eastus-1
  containers:
  - image: redis
    name: redis
  restartPolicy: Always
