apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis-zone2
  name: redis-zone2
spec:
  nodeSelector:
    topology.kubernetes.io/zone: eastus-2
  containers:
  - image: redis
    name: redis
  restartPolicy: Always
