apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srestrictingresshostname
  annotations:
    description: Restricts hostname for ingress
spec:
  crd:
    spec:
      names:
        kind: K8sRestrictIngressHostname # this must be the same name as the name on metadata.name (line 4)            
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            allowedhosts:
              type: array
              items:
                type: string        
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srestrictingresshostname

        violation[{"msg": msg}] {
          host := input.review.object.spec.rules[_].host
          not input_allowed_hosts(host)
          msg := sprintf("invalid ingress host %q", [host])
        }

        input_allowed_hosts(field) {
          endswith(field, input.parameters.allowedhosts[_])
        }