apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-ip-masq-agent-config
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    component: azure-ip-masq-agent
    kubernetes.io/cluster-service: "true"
data:
  ip-masq-agent: |-
    nonMasqueradeCIDRs:
      - 10.0.0.0/24 # Node Subnet CIDR
      - 10.0.1.0/24 # Pod Subnet CIDR
      - 10.100.0.0/16 # Service CIDR
    masqLinkLocal: false
    resyncInterval: 60s
