apiVersion: v1
data:
  ip-masq-agent: |-
    nonMasqueradeCIDRs:
      - 10.100.0.0/16
    masqLinkLocal: false
    resyncInterval: 60s
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    component: azure-ip-masq-agent
    kubernetes.io/cluster-service: "true"
  name: azure-ip-masq-agent-config
  namespace: kube-system
