apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  nodeSelector:
    agentpool: "ndv4pool"
  containers:
  - name: ubuntu
    image: ubuntu:20.04
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "apt-get update;apt-get install -y curl;while true; do sleep 30; done;" ]
    volumeMounts:
    - mountPath: /hostmnt
      name: host-mnt
  volumes:
  - name: host-mnt
    hostPath:
      path: /mnt
      type: Directory