apiVersion: v1
kind: Pod
metadata:
  name: wi-sql-test
  namespace: default
  labels:
    azure.workload.identity/use: "true"  
spec:
  serviceAccountName: wi-demo-sa
  containers:
    - image: wilab30894.azurecr.io/wi-sql-test
      name: wi-sql-test       
  nodeSelector:
    kubernetes.io/os: linux
